#!/usr/bin/env python3

import boto3

# 20-character alphanumeric external ID generated by customer and shared with PostPilot...
CUSTOMER_EXTERNAL_ID  = "20-random-alpha-chars"

# IAM Role ARN created and provided by PostPilot...
ROLE_ARN = "arn:aws:iam::000000000000:role/data-feed/postpilot-data-feed..."
# S3 Bucket name created and provided by PostPilot...
S3_BUCKET_NAME   = "postpilot-data-feed..."
S3_BUCKET_REGION = "us-east-2"


# Assume IAM Role in PostPilot customer-access account...
sts_client = boto3.client("sts", region_name=S3_BUCKET_REGION)
assume_role_response = sts_client.assume_role(
    RoleArn=ROLE_ARN,
    RoleSessionName="S3PutObjectSession",
    ExternalId=CUSTOMER_EXTERNAL_ID
)

credentials = assume_role_response["Credentials"]

# Initialize the S3 client with assumed temporary credentials...
s3_client = boto3.client(
    "s3",
    region_name=S3_BUCKET_REGION,
    aws_access_key_id=credentials["AccessKeyId"],
    aws_secret_access_key=credentials["SecretAccessKey"],
    aws_session_token=credentials["SessionToken"],
)

CUSTOMERS_FILE_NAME = "customers_2026032012.jsonl"
with open(f"/path/to/{CUSTOMERS_FILE_NAME}", "rb") as f:
    s3_client.put_object(
        Bucket=S3_BUCKET_NAME,
        Key=f"customers/{CUSTOMERS_FILE_NAME}",
        Body=f,
        ContentType="application/json",
    )

print(f"Successfully uploaded object 'customers/{CUSTOMERS_FILE_NAME}' to bucket '{S3_BUCKET_NAME}'...")

ORDERS_FILE_NAME = "orders_2026032012.jsonl"
with open(f"/path/to/{ORDERS_FILE_NAME}", "rb") as f:
    s3_client.put_object(
        Bucket=S3_BUCKET_NAME,
        Key=f"orders/{ORDERS_FILE_NAME}",
        Body=f,
        ContentType="application/json",
    )

print(f"Successfully uploaded object 'orders/{ORDERS_FILE_NAME}' to bucket '{S3_BUCKET_NAME}'...")
