#! /usr/bin/env ruby

require 'aws-sdk-s3'
require 'aws-sdk-sts'

# 20-character alphanumeric external ID generated by customer and shared with PostPilot...
CUSTOMER_EXTERNAL_ID  = "20-random-alpha-chars"

# IAM Role ARN created and provided by PostPilot...
ROLE_ARN = "arn:aws:iam::000000000000:role/data-feed/postpilot-data-feed..."
# S3 Bucket name created and provided by PostPilot...
S3_BUCKET_NAME = "postpilot-data-feed..."
S3_BUCKET_REGION = 'us-east-2'


# Assume IAM Role in PostPilot customer-access account...
sts_client = Aws::STS::Client.new
assume_role_response = sts_client.assume_role(
  role_arn:           ROLE_ARN,
  role_session_name: 'S3PutObjectSession',
  external_id:        CUSTOMER_EXTERNAL_ID
)

credentials = assume_role_response.credentials
temp_credentials = Aws::Credentials.new(
  credentials.access_key_id,
  credentials.secret_access_key,
  credentials.session_token
)

# Initialize the S3 client with assumed temporary credentials...
s3_client = Aws::S3::Client.new(credentials: temp_credentials, region: S3_BUCKET_REGION)

customers_file_name = "customers_2026022012.jsonl"
s3_client.put_object(
  bucket: S3_BUCKET_NAME,
  key:  "customers/#{customers_file_name}",
  body: File.read("path/to/#{customers_file_name}"),
  content_type: 'application/json'
)

puts "Successfully uploaded object 'customers/#{customers_file_name}' to bucket '#{S3_BUCKET_NAME}'..."

orders_file_name = "orders_2026022012.jsonl"
s3_client.put_object(
  bucket: S3_BUCKET_NAME,
  key:  "orders/#{orders_file_name}",
  body: File.read("path/to/#{orders_file_name}"),
  content_type: 'application/json'
)

puts "Successfully uploaded object 'orders/#{orders_file_name}' to bucket '#{S3_BUCKET_NAME}'..."
